backend:
  name: git-gateway
  branch: main
media_folder: 'public/img'
public_folder: '/img'
collections: 
  - name: 'blog'
    label: 'Blog'
    folder: 'src/blogs'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Gambar", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }